name: build_main

on:
  push:
    branches: ["dev"]

jobs:
  building-pipeline:
    name: ${{ github.ref }} building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]

    steps:
      - name: Checkout code for deployment
        uses: actions/checkout@v4

      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - run: setup .env
      - run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "${{ vars.DEV_ENV }}">.env
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "${{ vars.UAT_ENV }}">.env
          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            echo "${{ vars.PROD_ENV }}">.env
          fi

      - run: pnpm run build

      - name: Set environment variables
        run: |
          echo "HOST_PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "HOST_DNS=${{ secrets.DEV_HOST }}" >> $GITHUB_ENV
            echo "HOST_USERNAME=${{ secrets.DEV_HOST_USERNAME }}" >> $GITHUB_ENV
            echo "APP_NAME=dashboard_dev" >> $GITHUB_ENV
            echo "HOST_SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEV_SSH_KEY }}" >> $GITHUB_ENV

          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "HOST_DNS=${{ secrets.UAT_HOST }}" >> $GITHUB_ENV
            echo "HOST_USERNAME=${{ secrets.UAT_HOST_USERNAME }}" >> $GITHUB_ENV
            echo "APP_NAME=dashboard_uat" >> $GITHUB_ENV
            echo "HOST_SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.UAT_SSH_KEY }}" >> $GITHUB_ENV

          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            echo "HOST_DNS=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV
            echo "HOST_USERNAME=${{ secrets.PROD_HOST_USERNAME }}" >> $GITHUB_ENV
            echo "APP_NAME=dashboard_prod" >> $GITHUB_ENV
            echo "HOST_SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_SSH_KEY }}" >> $GITHUB_ENV
          fi

      - name: rsync deployments
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/ubuntu/"${{ env.APP_NAME }}"/
          remote_host: ${{ env.HOST_DNS }}
          remote_user: ${{ env.HOST_USERNAME }}
          remote_key: ${{ env.HOST_SSH_KEY }}

      - name: Start pm2 using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST_DNS }}
          username: ${{ env.HOST_USERNAME }}
          key: ${{ env.HOST_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/"${{ env.APP_NAME }}"/
            pm2 delete "${{ env.APP_NAME }}"
            pm2 start pnpm --name "${{ env.APP_NAME }}" -- start --port "${{ env.HOST_PORT }}"
            pm2 save
